
'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("b4665b57-8816-4fb8-9ecb-fe6d42f22529")>
#Region "EDM-Beziehungsmetadaten"
<Assembly: EdmRelationshipAttribute("BrisDataModel", "FK_Banana_Manufacturer", "Manufacturer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Models.Manufacturer), "Banana", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Models.Banana), True)>
<Assembly: EdmRelationshipAttribute("BrisDataModel", "FK_Banana_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Models.User), "Banana", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Models.Banana), True)>
<Assembly: EdmRelationshipAttribute("BrisDataModel", "FK_BananaConsumption_Banana", "Banana", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Models.Banana), "BananaConsumption", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Models.BananaConsumption), True)>
<Assembly: EdmRelationshipAttribute("BrisDataModel", "FK_BananaConsumption_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Models.User), "BananaConsumption", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Models.BananaConsumption), True)>
<Assembly: EdmRelationshipAttribute("BrisDataModel", "FK_RegistrationProcess_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Models.User), "RegistrationProcess", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Models.RegistrationProcess), True)>
<Assembly: EdmRelationshipAttribute("BrisDataModel", "FK_RolePermission_Role", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Models.Role), "RolePermission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Models.RolePermission), True)>
<Assembly: EdmRelationshipAttribute("BrisDataModel", "FK_User_Role", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Models.Role), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Models.User), True)>

#End Region

Namespace Models

    #Region "Kontexte"
    
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    Public Partial Class BrisDataEntities
        Inherits ObjectContext
    
        #Region "Konstruktoren"
    
        ''' <summary>
        ''' Initialisiert ein neues BrisDataEntities-Objekt mithilfe der in Abschnitt 'BrisDataEntities' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=BrisDataEntities", "BrisDataEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialisiert ein neues BrisDataEntities-Objekt.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "BrisDataEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialisiert ein neues BrisDataEntities-Objekt.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "BrisDataEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partielle Methoden"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet-Eigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        Public ReadOnly Property Banana() As ObjectSet(Of Banana)
            Get
                If (_Banana Is Nothing) Then
                    _Banana = MyBase.CreateObjectSet(Of Banana)("Banana")
                End If
                Return _Banana
            End Get
        End Property
    
        Private _Banana As ObjectSet(Of Banana)
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        Public ReadOnly Property BananaConsumption() As ObjectSet(Of BananaConsumption)
            Get
                If (_BananaConsumption Is Nothing) Then
                    _BananaConsumption = MyBase.CreateObjectSet(Of BananaConsumption)("BananaConsumption")
                End If
                Return _BananaConsumption
            End Get
        End Property
    
        Private _BananaConsumption As ObjectSet(Of BananaConsumption)
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        Public ReadOnly Property Manufacturer() As ObjectSet(Of Manufacturer)
            Get
                If (_Manufacturer Is Nothing) Then
                    _Manufacturer = MyBase.CreateObjectSet(Of Manufacturer)("Manufacturer")
                End If
                Return _Manufacturer
            End Get
        End Property
    
        Private _Manufacturer As ObjectSet(Of Manufacturer)
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        Public ReadOnly Property RegistrationProcess() As ObjectSet(Of RegistrationProcess)
            Get
                If (_RegistrationProcess Is Nothing) Then
                    _RegistrationProcess = MyBase.CreateObjectSet(Of RegistrationProcess)("RegistrationProcess")
                End If
                Return _RegistrationProcess
            End Get
        End Property
    
        Private _RegistrationProcess As ObjectSet(Of RegistrationProcess)
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        Public ReadOnly Property Role() As ObjectSet(Of Role)
            Get
                If (_Role Is Nothing) Then
                    _Role = MyBase.CreateObjectSet(Of Role)("Role")
                End If
                Return _Role
            End Get
        End Property
    
        Private _Role As ObjectSet(Of Role)
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        Public ReadOnly Property RolePermission() As ObjectSet(Of RolePermission)
            Get
                If (_RolePermission Is Nothing) Then
                    _RolePermission = MyBase.CreateObjectSet(Of RolePermission)("RolePermission")
                End If
                Return _RolePermission
            End Get
        End Property
    
        Private _RolePermission As ObjectSet(Of RolePermission)
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        Public ReadOnly Property User() As ObjectSet(Of User)
            Get
                If (_User Is Nothing) Then
                    _User = MyBase.CreateObjectSet(Of User)("User")
                End If
                Return _User
            End Get
        End Property
    
        Private _User As ObjectSet(Of User)

        #End Region

        #Region "AddTo-Methoden"
    
        ''' <summary>
        ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Banana'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
        ''' </summary>
        Public Sub AddToBanana(ByVal banana As Banana)
            MyBase.AddObject("Banana", banana)
        End Sub
    
        ''' <summary>
        ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'BananaConsumption'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
        ''' </summary>
        Public Sub AddToBananaConsumption(ByVal bananaConsumption As BananaConsumption)
            MyBase.AddObject("BananaConsumption", bananaConsumption)
        End Sub
    
        ''' <summary>
        ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Manufacturer'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
        ''' </summary>
        Public Sub AddToManufacturer(ByVal manufacturer As Manufacturer)
            MyBase.AddObject("Manufacturer", manufacturer)
        End Sub
    
        ''' <summary>
        ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'RegistrationProcess'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
        ''' </summary>
        Public Sub AddToRegistrationProcess(ByVal registrationProcess As RegistrationProcess)
            MyBase.AddObject("RegistrationProcess", registrationProcess)
        End Sub
    
        ''' <summary>
        ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Role'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
        ''' </summary>
        Public Sub AddToRole(ByVal role As Role)
            MyBase.AddObject("Role", role)
        End Sub
    
        ''' <summary>
        ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'RolePermission'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
        ''' </summary>
        Public Sub AddToRolePermission(ByVal rolePermission As RolePermission)
            MyBase.AddObject("RolePermission", rolePermission)
        End Sub
    
        ''' <summary>
        ''' Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'User'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet(Of T) '.
        ''' </summary>
        Public Sub AddToUser(ByVal user As User)
            MyBase.AddObject("User", user)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entitäten"
    
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="BrisDataModel", Name:="Banana")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Banana
        Inherits EntityObject
        #Region "Factory-Methode"
    
        ''' <summary>
        ''' Erstellt ein neues Banana-Objekt.
        ''' </summary>
        ''' <param name="id">Anfangswert der Eigenschaft Id.</param>
        ''' <param name="name">Anfangswert der Eigenschaft Name.</param>
        ''' <param name="fK_Manufacturer">Anfangswert der Eigenschaft FK_Manufacturer.</param>
        ''' <param name="radiation">Anfangswert der Eigenschaft Radiation.</param>
        Public Shared Function CreateBanana(id As Global.System.Guid, name As Global.System.String, fK_Manufacturer As Global.System.Guid, radiation As Global.System.Int32) As Banana
            Dim banana as Banana = New Banana
            banana.Id = id
            banana.Name = name
            banana.FK_Manufacturer = fK_Manufacturer
            banana.Radiation = radiation
            Return banana
        End Function

        #End Region

        #Region "Primitive Eigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Guid
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Guid
        Private Partial Sub OnIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Name() As Global.System.String
            Get
                Return _Name
            End Get
            Set
                OnNameChanging(value)
                ReportPropertyChanging("Name")
                _Name = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Name")
                OnNameChanged()
            End Set
        End Property
    
        Private _Name As Global.System.String
        Private Partial Sub OnNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnNameChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property FK_Manufacturer() As Global.System.Guid
            Get
                Return _FK_Manufacturer
            End Get
            Set
                OnFK_ManufacturerChanging(value)
                ReportPropertyChanging("FK_Manufacturer")
                _FK_Manufacturer = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("FK_Manufacturer")
                OnFK_ManufacturerChanged()
            End Set
        End Property
    
        Private _FK_Manufacturer As Global.System.Guid
        Private Partial Sub OnFK_ManufacturerChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnFK_ManufacturerChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Radiation() As Global.System.Int32
            Get
                Return _Radiation
            End Get
            Set
                OnRadiationChanging(value)
                ReportPropertyChanging("Radiation")
                _Radiation = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Radiation")
                OnRadiationChanged()
            End Set
        End Property
    
        Private _Radiation As Global.System.Int32
        Private Partial Sub OnRadiationChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnRadiationChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property FK_CreatedBy() As Nullable(Of Global.System.Guid)
            Get
                Return _FK_CreatedBy
            End Get
            Set
                OnFK_CreatedByChanging(value)
                ReportPropertyChanging("FK_CreatedBy")
                _FK_CreatedBy = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("FK_CreatedBy")
                OnFK_CreatedByChanged()
            End Set
        End Property
    
        Private _FK_CreatedBy As Nullable(Of Global.System.Guid)
        Private Partial Sub OnFK_CreatedByChanging(value As Nullable(Of Global.System.Guid))
        End Sub
    
        Private Partial Sub OnFK_CreatedByChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Barcode() As Global.System.String
            Get
                Return _Barcode
            End Get
            Set
                OnBarcodeChanging(value)
                ReportPropertyChanging("Barcode")
                _Barcode = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Barcode")
                OnBarcodeChanged()
            End Set
        End Property
    
        Private _Barcode As Global.System.String
        Private Partial Sub OnBarcodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnBarcodeChanged()
        End Sub

        #End Region

        #Region "Navigationseigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_Banana_Manufacturer", "Manufacturer")>
        Public Property Manufacturer() As Manufacturer
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Manufacturer)("BrisDataModel.FK_Banana_Manufacturer", "Manufacturer").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Manufacturer)("BrisDataModel.FK_Banana_Manufacturer", "Manufacturer").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property ManufacturerReference() As EntityReference(Of Manufacturer)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Manufacturer)("BrisDataModel.FK_Banana_Manufacturer", "Manufacturer")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Manufacturer)("BrisDataModel.FK_Banana_Manufacturer", "Manufacturer", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_Banana_User", "User")>
        Public Property User() As User
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BrisDataModel.FK_Banana_User", "User").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BrisDataModel.FK_Banana_User", "User").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property UserReference() As EntityReference(Of User)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BrisDataModel.FK_Banana_User", "User")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("BrisDataModel.FK_Banana_User", "User", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_BananaConsumption_Banana", "BananaConsumption")>
        Public Property BananaConsumption() As BananaConsumption
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of BananaConsumption)("BrisDataModel.FK_BananaConsumption_Banana", "BananaConsumption").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of BananaConsumption)("BrisDataModel.FK_BananaConsumption_Banana", "BananaConsumption").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property BananaConsumptionReference() As EntityReference(Of BananaConsumption)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of BananaConsumption)("BrisDataModel.FK_BananaConsumption_Banana", "BananaConsumption")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of BananaConsumption)("BrisDataModel.FK_BananaConsumption_Banana", "BananaConsumption", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="BrisDataModel", Name:="BananaConsumption")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class BananaConsumption
        Inherits EntityObject
        #Region "Factory-Methode"
    
        ''' <summary>
        ''' Erstellt ein neues BananaConsumption-Objekt.
        ''' </summary>
        ''' <param name="id">Anfangswert der Eigenschaft Id.</param>
        ''' <param name="fK_User">Anfangswert der Eigenschaft FK_User.</param>
        ''' <param name="fK_Banana">Anfangswert der Eigenschaft FK_Banana.</param>
        ''' <param name="amount">Anfangswert der Eigenschaft Amount.</param>
        Public Shared Function CreateBananaConsumption(id As Global.System.Guid, fK_User As Global.System.Guid, fK_Banana As Global.System.Guid, amount As Global.System.Int32) As BananaConsumption
            Dim bananaConsumption as BananaConsumption = New BananaConsumption
            bananaConsumption.Id = id
            bananaConsumption.FK_User = fK_User
            bananaConsumption.FK_Banana = fK_Banana
            bananaConsumption.Amount = amount
            Return bananaConsumption
        End Function

        #End Region

        #Region "Primitive Eigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Guid
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Guid
        Private Partial Sub OnIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property FK_User() As Global.System.Guid
            Get
                Return _FK_User
            End Get
            Set
                OnFK_UserChanging(value)
                ReportPropertyChanging("FK_User")
                _FK_User = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("FK_User")
                OnFK_UserChanged()
            End Set
        End Property
    
        Private _FK_User As Global.System.Guid
        Private Partial Sub OnFK_UserChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnFK_UserChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property FK_Banana() As Global.System.Guid
            Get
                Return _FK_Banana
            End Get
            Set
                OnFK_BananaChanging(value)
                ReportPropertyChanging("FK_Banana")
                _FK_Banana = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("FK_Banana")
                OnFK_BananaChanged()
            End Set
        End Property
    
        Private _FK_Banana As Global.System.Guid
        Private Partial Sub OnFK_BananaChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnFK_BananaChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Amount() As Global.System.Int32
            Get
                Return _Amount
            End Get
            Set
                OnAmountChanging(value)
                ReportPropertyChanging("Amount")
                _Amount = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Amount")
                OnAmountChanged()
            End Set
        End Property
    
        Private _Amount As Global.System.Int32
        Private Partial Sub OnAmountChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnAmountChanged()
        End Sub

        #End Region

        #Region "Navigationseigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_BananaConsumption_Banana", "Banana")>
        Public Property Banana() As Banana
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Banana)("BrisDataModel.FK_BananaConsumption_Banana", "Banana").Value
            End Get
            Set(value As Banana)
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Banana)("BrisDataModel.FK_BananaConsumption_Banana", "Banana").Value = Value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property BananaReference() As EntityReference(Of Banana)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Banana)("BrisDataModel.FK_BananaConsumption_Banana", "Banana")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Banana)("BrisDataModel.FK_BananaConsumption_Banana", "Banana", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_BananaConsumption_User", "User")>
        Public Property User() As User
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BrisDataModel.FK_BananaConsumption_User", "User").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BrisDataModel.FK_BananaConsumption_User", "User").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property UserReference() As EntityReference(Of User)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BrisDataModel.FK_BananaConsumption_User", "User")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("BrisDataModel.FK_BananaConsumption_User", "User", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="BrisDataModel", Name:="Manufacturer")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Manufacturer
        Inherits EntityObject
        #Region "Factory-Methode"
    
        ''' <summary>
        ''' Erstellt ein neues Manufacturer-Objekt.
        ''' </summary>
        ''' <param name="id">Anfangswert der Eigenschaft Id.</param>
        ''' <param name="name">Anfangswert der Eigenschaft Name.</param>
        Public Shared Function CreateManufacturer(id As Global.System.Guid, name As Global.System.String) As Manufacturer
            Dim manufacturer as Manufacturer = New Manufacturer
            manufacturer.Id = id
            manufacturer.Name = name
            Return manufacturer
        End Function

        #End Region

        #Region "Primitive Eigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Guid
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Guid
        Private Partial Sub OnIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Name() As Global.System.String
            Get
                Return _Name
            End Get
            Set
                OnNameChanging(value)
                ReportPropertyChanging("Name")
                _Name = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Name")
                OnNameChanged()
            End Set
        End Property
    
        Private _Name As Global.System.String
        Private Partial Sub OnNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnNameChanged()
        End Sub

        #End Region

        #Region "Navigationseigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_Banana_Manufacturer", "Banana")>
         Public Property Banana() As EntityCollection(Of Banana)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Banana)("BrisDataModel.FK_Banana_Manufacturer", "Banana")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Banana)("BrisDataModel.FK_Banana_Manufacturer", "Banana", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="BrisDataModel", Name:="RegistrationProcess")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class RegistrationProcess
        Inherits EntityObject
        #Region "Factory-Methode"
    
        ''' <summary>
        ''' Erstellt ein neues RegistrationProcess-Objekt.
        ''' </summary>
        ''' <param name="id">Anfangswert der Eigenschaft Id.</param>
        ''' <param name="fK_User">Anfangswert der Eigenschaft FK_User.</param>
        ''' <param name="randomValue">Anfangswert der Eigenschaft RandomValue.</param>
        ''' <param name="uniqueValue">Anfangswert der Eigenschaft UniqueValue.</param>
        ''' <param name="expirationDateTime">Anfangswert der Eigenschaft ExpirationDateTime.</param>
        Public Shared Function CreateRegistrationProcess(id As Global.System.Guid, fK_User As Global.System.Guid, randomValue As Global.System.Byte(), uniqueValue As Global.System.Guid, expirationDateTime As Global.System.DateTime) As RegistrationProcess
            Dim registrationProcess as RegistrationProcess = New RegistrationProcess
            registrationProcess.Id = id
            registrationProcess.FK_User = fK_User
            registrationProcess.RandomValue = randomValue
            registrationProcess.UniqueValue = uniqueValue
            registrationProcess.ExpirationDateTime = expirationDateTime
            Return registrationProcess
        End Function

        #End Region

        #Region "Primitive Eigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Guid
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Guid
        Private Partial Sub OnIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property FK_User() As Global.System.Guid
            Get
                Return _FK_User
            End Get
            Set
                OnFK_UserChanging(value)
                ReportPropertyChanging("FK_User")
                _FK_User = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("FK_User")
                OnFK_UserChanged()
            End Set
        End Property
    
        Private _FK_User As Global.System.Guid
        Private Partial Sub OnFK_UserChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnFK_UserChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property RandomValue() As Global.System.Byte()
            Get
                    Return StructuralObject.GetValidValue(_RandomValue)
            End Get
            Set
                OnRandomValueChanging(value)
                ReportPropertyChanging("RandomValue")
                _RandomValue = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("RandomValue")
                OnRandomValueChanged()
            End Set
        End Property
    
        Private _RandomValue As Global.System.Byte()
        Private Partial Sub OnRandomValueChanging(value As Global.System.Byte())
        End Sub
    
        Private Partial Sub OnRandomValueChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property UniqueValue() As Global.System.Guid
            Get
                Return _UniqueValue
            End Get
            Set
                OnUniqueValueChanging(value)
                ReportPropertyChanging("UniqueValue")
                _UniqueValue = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("UniqueValue")
                OnUniqueValueChanged()
            End Set
        End Property
    
        Private _UniqueValue As Global.System.Guid
        Private Partial Sub OnUniqueValueChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnUniqueValueChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ExpirationDateTime() As Global.System.DateTime
            Get
                Return _ExpirationDateTime
            End Get
            Set
                OnExpirationDateTimeChanging(value)
                ReportPropertyChanging("ExpirationDateTime")
                _ExpirationDateTime = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ExpirationDateTime")
                OnExpirationDateTimeChanged()
            End Set
        End Property
    
        Private _ExpirationDateTime As Global.System.DateTime
        Private Partial Sub OnExpirationDateTimeChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnExpirationDateTimeChanged()
        End Sub

        #End Region

        #Region "Navigationseigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_RegistrationProcess_User", "User")>
        Public Property User() As User
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BrisDataModel.FK_RegistrationProcess_User", "User").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BrisDataModel.FK_RegistrationProcess_User", "User").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property UserReference() As EntityReference(Of User)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of User)("BrisDataModel.FK_RegistrationProcess_User", "User")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of User)("BrisDataModel.FK_RegistrationProcess_User", "User", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="BrisDataModel", Name:="Role")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Role
        Inherits EntityObject
        #Region "Factory-Methode"
    
        ''' <summary>
        ''' Erstellt ein neues Role-Objekt.
        ''' </summary>
        ''' <param name="id">Anfangswert der Eigenschaft Id.</param>
        ''' <param name="name">Anfangswert der Eigenschaft Name.</param>
        Public Shared Function CreateRole(id As Global.System.Guid, name As Global.System.String) As Role
            Dim role as Role = New Role
            role.Id = id
            role.Name = name
            Return role
        End Function

        #End Region

        #Region "Primitive Eigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Guid
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Guid
        Private Partial Sub OnIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Name() As Global.System.String
            Get
                Return _Name
            End Get
            Set
                OnNameChanging(value)
                ReportPropertyChanging("Name")
                _Name = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Name")
                OnNameChanged()
            End Set
        End Property
    
        Private _Name As Global.System.String
        Private Partial Sub OnNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnNameChanged()
        End Sub

        #End Region

        #Region "Navigationseigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_RolePermission_Role", "RolePermission")>
         Public Property RolePermission() As EntityCollection(Of RolePermission)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of RolePermission)("BrisDataModel.FK_RolePermission_Role", "RolePermission")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of RolePermission)("BrisDataModel.FK_RolePermission_Role", "RolePermission", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_User_Role", "User")>
         Public Property User() As EntityCollection(Of User)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of User)("BrisDataModel.FK_User_Role", "User")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of User)("BrisDataModel.FK_User_Role", "User", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="BrisDataModel", Name:="RolePermission")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class RolePermission
        Inherits EntityObject
        #Region "Factory-Methode"
    
        ''' <summary>
        ''' Erstellt ein neues RolePermission-Objekt.
        ''' </summary>
        ''' <param name="id">Anfangswert der Eigenschaft Id.</param>
        ''' <param name="fK_Role">Anfangswert der Eigenschaft FK_Role.</param>
        ''' <param name="permission">Anfangswert der Eigenschaft Permission.</param>
        Public Shared Function CreateRolePermission(id As Global.System.Guid, fK_Role As Global.System.Guid, permission As Global.System.Int32) As RolePermission
            Dim rolePermission as RolePermission = New RolePermission
            rolePermission.Id = id
            rolePermission.FK_Role = fK_Role
            rolePermission.Permission = permission
            Return rolePermission
        End Function

        #End Region

        #Region "Primitive Eigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Guid
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Guid
        Private Partial Sub OnIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property FK_Role() As Global.System.Guid
            Get
                Return _FK_Role
            End Get
            Set
                OnFK_RoleChanging(value)
                ReportPropertyChanging("FK_Role")
                _FK_Role = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("FK_Role")
                OnFK_RoleChanged()
            End Set
        End Property
    
        Private _FK_Role As Global.System.Guid
        Private Partial Sub OnFK_RoleChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnFK_RoleChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Permission() As Global.System.Int32
            Get
                Return _Permission
            End Get
            Set
                OnPermissionChanging(value)
                ReportPropertyChanging("Permission")
                _Permission = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Permission")
                OnPermissionChanged()
            End Set
        End Property
    
        Private _Permission As Global.System.Int32
        Private Partial Sub OnPermissionChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnPermissionChanged()
        End Sub

        #End Region

        #Region "Navigationseigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_RolePermission_Role", "Role")>
        Public Property Role() As Role
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Role)("BrisDataModel.FK_RolePermission_Role", "Role").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Role)("BrisDataModel.FK_RolePermission_Role", "Role").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property RoleReference() As EntityReference(Of Role)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Role)("BrisDataModel.FK_RolePermission_Role", "Role")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Role)("BrisDataModel.FK_RolePermission_Role", "Role", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' Keine Dokumentation für Metadaten verfügbar.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="BrisDataModel", Name:="User")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class User
        Inherits EntityObject
        #Region "Factory-Methode"
    
        ''' <summary>
        ''' Erstellt ein neues User-Objekt.
        ''' </summary>
        ''' <param name="id">Anfangswert der Eigenschaft Id.</param>
        ''' <param name="name">Anfangswert der Eigenschaft Name.</param>
        ''' <param name="email">Anfangswert der Eigenschaft Email.</param>
        ''' <param name="passwordHash">Anfangswert der Eigenschaft PasswordHash.</param>
        ''' <param name="fK_Role">Anfangswert der Eigenschaft FK_Role.</param>
        Public Shared Function CreateUser(id As Global.System.Guid, name As Global.System.String, email As Global.System.String, passwordHash As Global.System.String, fK_Role As Global.System.Guid) As User
            Dim user as User = New User
            user.Id = id
            user.Name = name
            user.Email = email
            user.PasswordHash = passwordHash
            user.FK_Role = fK_Role
            Return user
        End Function

        #End Region

        #Region "Primitive Eigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Id() As Global.System.Guid
            Get
                Return _Id
            End Get
            Set
                If (_Id <> Value) Then
                    OnIdChanging(value)
                    ReportPropertyChanging("Id")
                    _Id = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Id")
                    OnIdChanged()
                End If
            End Set
        End Property
    
        Private _Id As Global.System.Guid
        Private Partial Sub OnIdChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIdChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Name() As Global.System.String
            Get
                Return _Name
            End Get
            Set
                OnNameChanging(value)
                ReportPropertyChanging("Name")
                _Name = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Name")
                OnNameChanged()
            End Set
        End Property
    
        Private _Name As Global.System.String
        Private Partial Sub OnNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnNameChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Email() As Global.System.String
            Get
                Return _Email
            End Get
            Set
                OnEmailChanging(value)
                ReportPropertyChanging("Email")
                _Email = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Email")
                OnEmailChanged()
            End Set
        End Property
    
        Private _Email As Global.System.String
        Private Partial Sub OnEmailChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnEmailChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property PasswordHash() As Global.System.String
            Get
                Return _PasswordHash
            End Get
            Set
                OnPasswordHashChanging(value)
                ReportPropertyChanging("PasswordHash")
                _PasswordHash = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("PasswordHash")
                OnPasswordHashChanged()
            End Set
        End Property
    
        Private _PasswordHash As Global.System.String
        Private Partial Sub OnPasswordHashChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPasswordHashChanged()
        End Sub
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property FK_Role() As Global.System.Guid
            Get
                Return _FK_Role
            End Get
            Set
                OnFK_RoleChanging(value)
                ReportPropertyChanging("FK_Role")
                _FK_Role = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("FK_Role")
                OnFK_RoleChanged()
            End Set
        End Property
    
        Private _FK_Role As Global.System.Guid
        Private Partial Sub OnFK_RoleChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnFK_RoleChanged()
        End Sub

        #End Region

        #Region "Navigationseigenschaften"
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_Banana_User", "Banana")>
        Public Property Banana() As Banana
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Banana)("BrisDataModel.FK_Banana_User", "Banana").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Banana)("BrisDataModel.FK_Banana_User", "Banana").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property BananaReference() As EntityReference(Of Banana)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Banana)("BrisDataModel.FK_Banana_User", "Banana")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Banana)("BrisDataModel.FK_Banana_User", "Banana", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_BananaConsumption_User", "BananaConsumption")>
         Public Property BananaConsumption() As EntityCollection(Of BananaConsumption)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of BananaConsumption)("BrisDataModel.FK_BananaConsumption_User", "BananaConsumption")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of BananaConsumption)("BrisDataModel.FK_BananaConsumption_User", "BananaConsumption", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_RegistrationProcess_User", "RegistrationProcess")>
        Public Property RegistrationProcess() As RegistrationProcess
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of RegistrationProcess)("BrisDataModel.FK_RegistrationProcess_User", "RegistrationProcess").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of RegistrationProcess)("BrisDataModel.FK_RegistrationProcess_User", "RegistrationProcess").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property RegistrationProcessReference() As EntityReference(Of RegistrationProcess)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of RegistrationProcess)("BrisDataModel.FK_RegistrationProcess_User", "RegistrationProcess")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of RegistrationProcess)("BrisDataModel.FK_RegistrationProcess_User", "RegistrationProcess", value)
                End If
            End Set
        End Property
    
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("BrisDataModel", "FK_User_Role", "Role")>
        Public Property Role() As Role
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Role)("BrisDataModel.FK_User_Role", "Role").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Role)("BrisDataModel.FK_User_Role", "Role").Value = value
            End Set
        End Property
        ''' <summary>
        ''' Keine Dokumentation für Metadaten verfügbar.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property RoleReference() As EntityReference(Of Role)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Role)("BrisDataModel.FK_User_Role", "Role")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Role)("BrisDataModel.FK_User_Role", "Role", value)
                End If
            End Set
        End Property

        #End Region

    End Class

    #End Region

    
End Namespace
